//! Proto round-trip tests for the Stage-3 sidecar command extensions:
//! create_playlist, add_playlist_items, get_liked_songs, get_artist,
//! get_song_related, get_album.
//!
//! Each command has a request-serialization test (the wire line the sidecar
//! receives) and a response-parsing test (the wire line the sidecar sends
//! back). The wire format is `{"ok":true,"data":{"key":value}}` for responses
//! and `{"cmd":"snake_case_name",...}` for requests — matching the existing
//! proto tests in `tests/yt_sidecar.rs`.

use jukebox::yt::proto::*;

// ---------------------------------------------------------------------------
// create_playlist
// ---------------------------------------------------------------------------

#[test]
fn create_playlist_request_serializes() {
    let req = Request::CreatePlaylist {
        title: "My Mix".into(),
        description: "Generated by jukebox".into(),
        privacy: "PRIVATE".into(),
        video_ids: vec!["abc123".into(), "def456".into()],
    };
    let line = req.to_line();
    assert!(line.contains("\"cmd\":\"create_playlist\""));
    assert!(line.contains("\"title\":\"My Mix\""));
    assert!(line.contains("\"privacy\":\"PRIVATE\""));
    assert!(line.contains("\"video_ids\":[\"abc123\",\"def456\"]"));
    assert!(!line.contains('\n')); // single line
}

#[test]
fn create_playlist_request_minimal() {
    // Empty description + empty video_ids + empty privacy (serde defaults).
    let req = Request::CreatePlaylist {
        title: "T".into(),
        description: String::new(),
        privacy: String::new(),
        video_ids: Vec::new(),
    };
    let line = req.to_line();
    assert!(line.contains("\"cmd\":\"create_playlist\""));
    assert!(line.contains("\"title\":\"T\""));
}

#[test]
fn create_playlist_response_parses() {
    let line = r#"{"ok":true,"data":{"created_playlist":{"id":"PL123","title":"My Mix","privacy":"PRIVATE"}}}"#;
    let resp = Response::from_line(line).unwrap();
    match resp {
        Response::CreatedPlaylist { id, title, privacy } => {
            assert_eq!(id, "PL123");
            assert_eq!(title, "My Mix");
            assert_eq!(privacy, "PRIVATE");
        }
        other => panic!("expected CreatedPlaylist, got {other:?}"),
    }
}

#[test]
fn create_playlist_response_missing_fields_default() {
    // Missing fields → serde defaults (empty strings).
    let line = r#"{"ok":true,"data":{"created_playlist":{"id":"PL1"}}}"#;
    let resp = Response::from_line(line).unwrap();
    match resp {
        Response::CreatedPlaylist { id, title, privacy } => {
            assert_eq!(id, "PL1");
            assert_eq!(title, "");
            assert_eq!(privacy, "");
        }
        other => panic!("expected CreatedPlaylist, got {other:?}"),
    }
}

// ---------------------------------------------------------------------------
// add_playlist_items
// ---------------------------------------------------------------------------

#[test]
fn add_playlist_items_request_serializes() {
    let req = Request::AddPlaylistItems {
        playlist_id: "PL123".into(),
        video_ids: vec!["v1".into(), "v2".into()],
        duplicates: true,
    };
    let line = req.to_line();
    assert!(line.contains("\"cmd\":\"add_playlist_items\""));
    assert!(line.contains("\"playlist_id\":\"PL123\""));
    assert!(line.contains("\"video_ids\":[\"v1\",\"v2\"]"));
    assert!(line.contains("\"duplicates\":true"));
}

#[test]
fn add_playlist_items_response_parses() {
    let line = r#"{"ok":true,"data":{"added_items":{"status":"STATUS_SUCCEEDED","count":3}}}"#;
    let resp = Response::from_line(line).unwrap();
    match resp {
        Response::AddedItems { status, count } => {
            assert_eq!(status, "STATUS_SUCCEEDED");
            assert_eq!(count, 3);
        }
        other => panic!("expected AddedItems, got {other:?}"),
    }
}

#[test]
fn add_playlist_items_response_missing_fields_default() {
    let line = r#"{"ok":true,"data":{"added_items":{}}}"#;
    let resp = Response::from_line(line).unwrap();
    match resp {
        Response::AddedItems { status, count } => {
            assert_eq!(status, "");
            assert_eq!(count, 0);
        }
        other => panic!("expected AddedItems, got {other:?}"),
    }
}

// ---------------------------------------------------------------------------
// get_liked_songs
// ---------------------------------------------------------------------------

#[test]
fn get_liked_songs_request_serializes() {
    let req = Request::GetLikedSongs { limit: 100 };
    let line = req.to_line();
    assert!(line.contains("\"cmd\":\"get_liked_songs\""));
    assert!(line.contains("\"limit\":100"));
}

#[test]
fn get_liked_songs_response_parses() {
    let line = r#"{"ok":true,"data":{"liked_songs":[{"video_id":"v1","title":"Song","artist":"Artist","album":null,"dur":null,"isrc":null}]}}"#;
    let resp = Response::from_line(line).unwrap();
    match resp {
        Response::LikedSongs(v) => {
            assert_eq!(v.len(), 1);
            assert_eq!(v[0].video_id, "v1");
            assert_eq!(v[0].title, "Song");
            assert_eq!(v[0].artist, "Artist");
        }
        other => panic!("expected LikedSongs, got {other:?}"),
    }
}

#[test]
fn get_liked_songs_response_empty_list() {
    let line = r#"{"ok":true,"data":{"liked_songs":[]}}"#;
    let resp = Response::from_line(line).unwrap();
    match resp {
        Response::LikedSongs(v) => assert!(v.is_empty()),
        other => panic!("expected LikedSongs, got {other:?}"),
    }
}

// ---------------------------------------------------------------------------
// get_artist
// ---------------------------------------------------------------------------

#[test]
fn get_artist_request_serializes() {
    let req = Request::GetArtist {
        channel_id: "UCM123".into(),
    };
    let line = req.to_line();
    assert!(line.contains("\"cmd\":\"get_artist\""));
    assert!(line.contains("\"channel_id\":\"UCM123\""));
}

#[test]
fn get_artist_response_parses() {
    let line = r#"{"ok":true,"data":{"artist_info":{"name":"Adele","channel_id":"UCM123","shuffle_id":"RASM","radio_id":"RADM","subscribers":"50M","description":"Singer","songs_browse_id":"PL123","songs":[{"video_id":"v1","title":"Hello","artist":"Adele","album":null,"dur":null,"isrc":null}],"related":[{"name":"Sam Smith","browse_id":"UC456"}]}}}"#;
    let resp = Response::from_line(line).unwrap();
    match resp {
        Response::ArtistInfo(a) => {
            assert_eq!(a.name, "Adele");
            assert_eq!(a.channel_id, "UCM123");
            assert_eq!(a.shuffle_id, "RASM");
            assert_eq!(a.radio_id, "RADM");
            assert_eq!(a.subscribers, "50M");
            assert_eq!(a.description, "Singer");
            assert_eq!(a.songs_browse_id, "PL123");
            assert_eq!(a.songs.len(), 1);
            assert_eq!(a.songs[0].video_id, "v1");
            assert_eq!(a.songs[0].title, "Hello");
            assert_eq!(a.related.len(), 1);
            assert_eq!(a.related[0].name, "Sam Smith");
            assert_eq!(a.related[0].browse_id, "UC456");
        }
        other => panic!("expected ArtistInfo, got {other:?}"),
    }
}

#[test]
fn get_artist_response_missing_optionals_default() {
    // Only `name` is required; all other fields have serde defaults.
    let line = r#"{"ok":true,"data":{"artist_info":{"name":"Unknown"}}}"#;
    let resp = Response::from_line(line).unwrap();
    match resp {
        Response::ArtistInfo(a) => {
            assert_eq!(a.name, "Unknown");
            assert_eq!(a.channel_id, "");
            assert_eq!(a.shuffle_id, "");
            assert_eq!(a.radio_id, "");
            assert_eq!(a.subscribers, "");
            assert_eq!(a.description, "");
            assert_eq!(a.songs_browse_id, "");
            assert!(a.songs.is_empty());
            assert!(a.related.is_empty());
        }
        other => panic!("expected ArtistInfo, got {other:?}"),
    }
}

// ---------------------------------------------------------------------------
// get_song_related
// ---------------------------------------------------------------------------

#[test]
fn get_song_related_request_serializes() {
    let req = Request::GetSongRelated {
        browse_id: "RAMP1".into(),
    };
    let line = req.to_line();
    assert!(line.contains("\"cmd\":\"get_song_related\""));
    assert!(line.contains("\"browse_id\":\"RAMP1\""));
}

#[test]
fn get_song_related_response_parses() {
    let line = r#"{"ok":true,"data":{"related_content":{"tracks":[{"video_id":"v1","title":"Song","artist":"Artist","album":null,"dur":null,"isrc":null}],"playlists":[{"id":"PL1","name":"Mix","count":0}]}}}"#;
    let resp = Response::from_line(line).unwrap();
    match resp {
        Response::RelatedContent { tracks, playlists } => {
            assert_eq!(tracks.len(), 1);
            assert_eq!(tracks[0].video_id, "v1");
            assert_eq!(playlists.len(), 1);
            assert_eq!(playlists[0].id, "PL1");
            assert_eq!(playlists[0].name, "Mix");
            assert_eq!(playlists[0].count, 0);
        }
        other => panic!("expected RelatedContent, got {other:?}"),
    }
}

#[test]
fn get_song_related_response_empty() {
    let line = r#"{"ok":true,"data":{"related_content":{"tracks":[],"playlists":[]}}}"#;
    let resp = Response::from_line(line).unwrap();
    match resp {
        Response::RelatedContent { tracks, playlists } => {
            assert!(tracks.is_empty());
            assert!(playlists.is_empty());
        }
        other => panic!("expected RelatedContent, got {other:?}"),
    }
}

#[test]
fn get_song_related_response_missing_lists_default() {
    // Missing tracks/playlists → empty vecs (from_line uses unwrap_or_default).
    let line = r#"{"ok":true,"data":{"related_content":{}}}"#;
    let resp = Response::from_line(line).unwrap();
    match resp {
        Response::RelatedContent { tracks, playlists } => {
            assert!(tracks.is_empty());
            assert!(playlists.is_empty());
        }
        other => panic!("expected RelatedContent, got {other:?}"),
    }
}

// ---------------------------------------------------------------------------
// get_album
// ---------------------------------------------------------------------------

#[test]
fn get_album_request_serializes() {
    let req = Request::GetAlbum {
        browse_id: "MPMb123".into(),
    };
    let line = req.to_line();
    assert!(line.contains("\"cmd\":\"get_album\""));
    assert!(line.contains("\"browse_id\":\"MPMb123\""));
}

#[test]
fn get_album_response_parses() {
    let line = r#"{"ok":true,"data":{"album_info":{"title":"25","artists":[{"name":"Adele","browse_id":"UCM123"}],"year":"2015","tracks":[{"video_id":"v1","title":"Hello","artist":"Adele","album":null,"dur":null,"isrc":null}]}}}"#;
    let resp = Response::from_line(line).unwrap();
    match resp {
        Response::AlbumInfo(a) => {
            assert_eq!(a.title, "25");
            assert_eq!(a.artists.len(), 1);
            assert_eq!(a.artists[0].name, "Adele");
            assert_eq!(a.artists[0].browse_id, "UCM123");
            assert_eq!(a.year, "2015");
            assert_eq!(a.tracks.len(), 1);
            assert_eq!(a.tracks[0].video_id, "v1");
            assert_eq!(a.tracks[0].title, "Hello");
        }
        other => panic!("expected AlbumInfo, got {other:?}"),
    }
}

#[test]
fn get_album_response_missing_optionals_default() {
    // Only `title` is required; artists/year/tracks have serde defaults.
    let line = r#"{"ok":true,"data":{"album_info":{"title":"Untitled"}}}"#;
    let resp = Response::from_line(line).unwrap();
    match resp {
        Response::AlbumInfo(a) => {
            assert_eq!(a.title, "Untitled");
            assert!(a.artists.is_empty());
            assert_eq!(a.year, "");
            assert!(a.tracks.is_empty());
        }
        other => panic!("expected AlbumInfo, got {other:?}"),
    }
}

// ---------------------------------------------------------------------------
// Struct-level deserialization (ArtistSummary, AlbumSummary, RelatedArtist)
// ---------------------------------------------------------------------------

#[test]
fn related_artist_deserializes() {
    let json = r#"{"name":"Sam Smith","browse_id":"UC456"}"#;
    let r: RelatedArtist = serde_json::from_str(json).unwrap();
    assert_eq!(r.name, "Sam Smith");
    assert_eq!(r.browse_id, "UC456");
}

#[test]
fn related_artist_missing_browse_id_defaults() {
    let json = r#"{"name":"Unknown"}"#;
    let r: RelatedArtist = serde_json::from_str(json).unwrap();
    assert_eq!(r.name, "Unknown");
    assert_eq!(r.browse_id, "");
}

#[test]
fn artist_summary_deserializes() {
    let json = r#"{"name":"Adele","channel_id":"UC1","shuffle_id":"RAS","radio_id":"RAD","subscribers":"50M","description":"Singer","songs_browse_id":"PL1","songs":[],"related":[]}"#;
    let a: ArtistSummary = serde_json::from_str(json).unwrap();
    assert_eq!(a.name, "Adele");
    assert_eq!(a.channel_id, "UC1");
    assert_eq!(a.shuffle_id, "RAS");
    assert_eq!(a.radio_id, "RAD");
    assert!(a.songs.is_empty());
    assert!(a.related.is_empty());
}

#[test]
fn album_summary_deserializes() {
    let json = r#"{"title":"25","artists":[{"name":"Adele","browse_id":"UC1"}],"year":"2015","tracks":[]}"#;
    let a: AlbumSummary = serde_json::from_str(json).unwrap();
    assert_eq!(a.title, "25");
    assert_eq!(a.artists.len(), 1);
    assert_eq!(a.year, "2015");
    assert!(a.tracks.is_empty());
}

// ---------------------------------------------------------------------------
// Error response for new commands
// ---------------------------------------------------------------------------

#[test]
fn error_response_for_new_command() {
    // A sidecar error for any new command surfaces as Response::Error.
    let line = r#"{"ok":false,"error":"create_playlist failed: not authenticated"}"#;
    let resp = Response::from_line(line).unwrap();
    assert!(matches!(resp, Response::Error(e) if e.contains("create_playlist")));
}
